### ISSUE TITLE
False positives on SDCC-generated asm

### ISSUE THREAD

**Issue by spth** [santiontanon/mdlz80optimizer#26]
I've run mdl -po on some asm generated by current SDCC 4.1.12 (the C standard library that comes with SDCC, compiled for the z80 port), but about half of the results are false positives of the following two kinds.

~~~~
INFO: Pattern-based optimization in acosf.asm#104: Replace call _asincosf; ret with jp _asincosf (1 bytes, 18 t-states saved)
~~~~

Here, _asincosf takes a parameter on the stack; when replacing ret with jp, that parameter would no longer be at the position relative to sp expected in _asincosf. I have no idea how mdl could handle that.

~~~~
INFO: Pattern-based optimization in c16stombs.asm#143: Remove push iy / pop iy as register is not modified in between (4 bytes, 33 t-states saved)
~~~~

Here, an instruction in between the push iy and the pop iy accesses the stack location iy is pushed to (via the frame pointer ix). To handle this, mdl would have to track the value in ix (SDCC typically just sets it up as stack frame at function entry).

**Comment by santiontanon** [comment]
Hi spth! Oh, I see, so _asincosf expects the parameter to be 4 bytes away in the stack, instead of 2... hmm... I see. In that case the code of _asincosf would have to be modified accordingly. I see two solutions to this:
1) add a check in MDL to verify that _asincosf does not make explicit use of stack offsets (and if it does, prevent the optimization)
2) figure out some logic with which mdl could actually modify those offsets

Do you have some example code snippet of how does the SDCC code looks like? for example how does _asincosf look (I just want to see exactly how does the code that SDCC generates to access the stack variable looks like, so MDL can easily detect some of those patterns).

And about the second, oh! interesting case! Ok, this is something that I'd have to add a check for. MDL already has some checks to see if the program is using the stack in between push/pop, but it clearly does not detect it when the pointer to the stack was set _before_ the push/pop into IX. Thanks for reporting!

**Comment by spth** [comment]
I've attached two relevant files:

[acosf.asm.gz](https://github.com/santiontanon/mdlz80optimizer/files/7252794/acosf.asm.gz)
[asincosf.asm.gz](https://github.com/santiontanon/mdlz80optimizer/files/7252795/asincosf.asm.gz)

Regarding sample code: I you use GNU/Linux or similar, you can just download current SDCC from the repository. A ./configure --disable-pic14-port --disable-pic16-port; make -j 18 will build it, including the standard libraries. The you can find Assembler source as .s (hand-written) and .am (compiler-generated) for the standard library in device/lib/z80, device/lib/z80n, device/lib/z180.
If you want even more asm code, you can build the regression tests (make --no-print-directory test-z80 -j 18 in support/regression), then you'll find asm generated from the regression tests (and there are lots of them) in support/regression/gen.

**Comment by santiontanon** [comment]
Great! Thanks a lot! I'll take a look at this and at issue #27 over the weekend! :)

**Comment by santiontanon** [comment]
Apologies for taking so long to look into this, but I think the new development version ( https://github.com/santiontanon/mdlz80optimizer/releases/tag/v2.2 ) should resolve this issue! (I'll resolve the issue, but if this does not solve completely, by all means, please reopen the issue, and I'll look into it!). Thanks again for reporting, and for the example source code!
