### ISSUE TITLE
Z80N and Z180 support

### ISSUE THREAD

**Issue by spth** [santiontanon/mdlz80optimizer#27]
The Z80N and Z180 are very similar to the Z80, as they only add few instructions. So it should not require too much effor to support them in mdl.

Even if the Z80N and Z180 instructions are not optimized, it would already be helpful, if normal Z80 code in a file that also contains some Z80N- or Z180-specific instructions could be optimized.

For sdasz80, this could be autodetected, as the assembler files for Z80N contain a .zxn to switch to the Z80N instruction set, and those for Z180 contain .hd64.

**Comment by santiontanon** [comment]
Indeed! This would be very nice! I already had a "to do" item to add support for Z80N, but Z180 would be even easier I think, as it's only one extra instruction, and then adjusting the timings of the rest.

Do you have any pointer to any github o any other available source code online where I can get examples of Z80N or Z180 source code to use as tests?

**Comment by spth** [comment]
The Z180 has a few new instructions: mul, tst, slp and various I/O instructions.
In the "Z8018x Family MPU Manual" they are marked by two stars in the "Instruction Summary" section.
For asm source, see the my reply to issue #26.

**Comment by santiontanon** [comment]
Quick update on this issue: Z80next support has already been added (starting from the current preliminary 2.2 release: https://github.com/santiontanon/mdlz80optimizer/releases/tag/v2.2 ). 

I'll be working to add support for Z180 before the final 2.2 release. This one is taking a bit longer, since, if I am reading the z180 manual correctly, the timing of all regular z80 instructions is slightly different in the z180, so, I need to create a complete new instructions table for this CPU to make sure all timings are correct.

**Comment by santiontanon** [comment]
Z80n and z180 are supported in the latest preliminary release, and will be included in the upcoming v2.2. Closing this issue, but feel free to re-open it if there are any problems :)
