### ISSUE TITLE
Use of multiple directives in sjasmplus

### ISSUE THREAD

**Issue by abekermsx** [santiontanon/mdlz80optimizer#32]
When assembling code with --dirbol specified on the commandline, sjasmplus allows lines to start with a directive and to have (one) extra directive on the same line (without putting the character : between the directives).

It allows for constructs like this:
db 0,0,0 dw 0

**Comment by ped7g** [comment]
oh.. wow... but that's rather bug in sjasmplus, not wanted feature. This is just wrong. I'll probably fix it in next version.

**Comment by santiontanon** [comment]
lol!! So, should I just ignore then? Is there any codebase that exploits this? :)

**Comment by abekermsx** [comment]
I found it in the code for that super cool SNES platformer port.
https://download.file-hunter.com/Source%20Codes/

**Comment by ped7g** [comment]
oh, that one *chuckle*... I believe I did fix all of those when I was helping migrating the project to sjasmplus, so I guess I either overlooked few or few were added after the migration when the project was finished. Doing quick regex search with `^(db|dw)[^:]+\s(db|dw)\s` pattern it seems there's only ~45 of them, so should be reasonably easy to patch by hand.

I will definitely fix it in sjasmplus itself for next release, so then the project will not build any more with latest version (as the project is already finished, I doubt that's a huge issue, the older versions of sjasmplus are still available).

Santion: no idea what you want to do about it, whether you want to support quirky behaviour or not, I personally wouldn't.

I understand it's better to not patch other projects if they are considered "finished", but if you are just curious about mdlz80 performance, doing quick and dirty edit of few lines is IMHO better option than introducing bug into the tool. If you are seriously considering to continue work on MSW project, then the source should be definitely fixed, no question about that. :)

**Comment by santiontanon** [comment]
haha, look at line 3594 in this file: https://github.com/GuillianSeed/MetalGear/blob/master/constants/structures.asm

There is a weird "struc" keyword after "STRUCT	SOUND", which should not be there I think, but sjasm seems to ignore it. I added a special case in MDL for that.

Concerning this bug, I think what I'm currently leaning to to do is to define a "sjasmplus1.18.3" dialect name that supports multiple directives in one line, and keep the "sjasmplus" name reserved for the most up-to-date sjasmplus, which will not support it. In this way, if one really wants to, MDL can be used with codebases that exploit this bug.

**Comment by ped7g** [comment]
> haha, look at line 3594 in this file: https://github.com/GuillianSeed/MetalGear/blob/master/constants/structures.asm

yeah, that would not work in current sjasmplus (which is anyway quite somewhat distant relative to sjasm, so there are some serious differences in syntax now, even the non-bug cases).

```
test.asm(50): error: [STRUCT] syntax error, unexpected: struc
 50   0000              	STRUCT	SOUND		    struc ; (sizeof=0x20)		    ; ...
```

> There is a weird "struc" keyword after "STRUCT SOUND", which should not be there I think, but sjasm seems to ignore it. I added a special case in MDL for that (but notice that is "sjasm", not "sjasmplus")

yes, sjasmplus did fork from sjasm long time ago, and then the sjasmplus further forked several times and I'm co-maintaining only z00m's fork, so.. can't do anything about this. But I would probably try to fix the MG source instead than adding quirk to MDL. :) (I'm sometimes very annoying with this approach of "make things properly and fix the real bug") :)

(BTW, if you want to support the quirk with version dialect, then this bug happens only when directives are enabled at beginning of line `--dirbol` and when the first directive starts at beginning of line, haven't check the source yet, but I guess the first optional parseLabel will note the directive and process it, and then the proper parse directive will process the second one, and nobody demands delimiter between them (as those are internally transparent to parser, receiving each part of line as new line each time, and skipping label parsing for 2+ part).

**Comment by santiontanon** [comment]
Good point. I just reported that "struc" keyword to Manuel to fix it, and once it's fixed, I'll remove that exception from the MDL codebase :)

I am thinking that rather than defining a separate specific dialect, I might add a series of flags for these "quirks" that are all disabled by default, but that enable supporting some of these weird things explicitly just in case, and will produce warnings indicating which source lines contain these, to help fixing them.

**Comment by santiontanon** [comment]
Alright, what I decided to do was to add two separate flags to enable MDL to parse these weird syntax anomalies. The one for the anomaly reported in this issue is "-quirk-sjasmplus-dirbol-double-directive". So, by default MDL will not support this, but you can force it to.

This was fixed in this commit: https://github.com/santiontanon/mdlz80optimizer/commit/2a544a8639ccb5a02fbd3e93261647cdfaf449e6

With all these changes, I was able to run MDL on "that project" using:

java -jar mdl.jar -dialect sjasmplus ../[first file].asm [second file].asm -quirk-sjasmplus-dirbol-double-directive -po

You can also add the "-ro" flag, but in this code base, I noticed that there are warnings since some assembler files are included more than once, and hence there is code that is repeated more than once (not sure if that was intended, notice MDL generates warnings for those). Because of that "-ro" keeps wanting to remove the replicated code, and you'll get LOTs of code optimizations for space, but I'm not sure if those are relevant.

This will be included in the upcoming release, but you can try it with this pre-release: https://github.com/santiontanon/mdlz80optimizer/releases/tag/v2.3dev
