### ISSUE TITLE
Invalid optimization for out using BC

### ISSUE THREAD

**Issue by taylorza** [santiontanon/mdlz80optimizer#37]
The "Pattern Based" optimization is potentially incorrect when the high byte is used for the `out` op.

Original Code
```
ld bc, 0x303b           
out (c), a
```

MDL optimization
```
INFO: Pattern-based optimization in code.asm#1123: Replace ld bc,#303b with ld c,(#303b) & #00ff (1 bytes, 3 t-states saved)
```

Resulting code (B not loaded with 0x30)
```
ld c, 59
out (c), a
```

**Comment by santiontanon** [comment]
Thanks for reporting! 

Quick question: did you try this on an MSX, Spectrum or Amstrad project?

This is an expected optimization in MSX, where the "in/out" addresses are 8bit (and just using C), but in Spectrum/Amstrad, "in/out" addresses are 16 bits (using BC). By default, MDL assumes you are using an MSX (sorry about that, haha), and hence it'll do this optimization. If you are targeting a Spectrum, use the "-cpu z80" flag, and if you are targeting an Amstrad, use the "-cpu z80cpc".

Let me know if that's the issue. Otherwise, I'll look to see where is the bug :)

**Comment by taylorza** [comment]
You are welcome, and thanks for a very helpful tool.

I am targeting a ZX Spectrum, specifically the ZX Spectrum Next but for this I was not using any of the extended OP Codes so that should not have interfered.

I will test the `-cpu Z80` flag this evening and let you know how that goes.

**Comment by santiontanon** [comment]
Cool!! Thanks!! I recently added ZX Nest support (with ```-cpu z80next```), but I have only tested it with one project. So, I would not be surprised if I got something wrong in the extended op codes haha. If you encounter any issues, do let me know :)

**Comment by taylorza** [comment]
Using the -cpu Z80 option cleared that right up. Thank you.

**Comment by taylorza** [comment]
I did a quick test with `-cpu z80next`, the -so option sends the optimizer into an infinite loop, but I will work on a simple reproduction and get back to you.

**Comment by santiontanon** [comment]
Thanks!!! Any sample code that causes the issue is appreciated! :) (warning: the -so optimizer is quite slow, haha :) )
