### ISSUE TITLE
Proposes wrongly to delete IM 2 initialization

### ISSUE THREAD

**Issue by ruyrybeyro** [santiontanon/mdlz80optimizer#45]
Hi,

The output for the Z80 asm code:

        LD      A,$FE
        LD      I,A             ; fetch interrupt address from FEFF
        IM      2               ; turn IM2 on

Should not be, as it is now:

    INFO: Search-based optimization in hz.asm#11: replace ld a, #fe; ld i, a with  (4 bytes, 16 t-states saved)
    DIGGEST: SearchBasedOptimizer: 1 optimizations applied, 4 bytes, 16 t-states saved.

I am running the command with the following options:

    java -jar mdl.jar hz.asm  -dialect pasmo -asm t.asm -so -cpu z80

Regards

**Comment by santiontanon** [comment]
Oh, very interesting! I probably have the dependencies for "im 2" incomplete! I'll take a look after work.

**Comment by santiontanon** [comment]
Alright, fixed in a recent commit! It turns out the search-based optimizer was ignoring register "i" completely! I just added it to the list of registers being tracked, and it seems to fix the problem. Thanks for reporting!

Again, if you compile from source from github, the fix is already there. But otherwise, I updated the temporary latest build here: https://braingames.santiontanon.dev/uploads/tmp/mdl.jar
